version: '3'

services:
  app_venta:
    build: proyect_tienda
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://tienda_ventas_bd:3306/tienda_ventas?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      tienda_ventas_bd:
          condition: service_healthy
  tienda_ventas_bd:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: tienda_ventas
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10